### PR TITLE
Add a dos inspired theme for oh-my-zsh

### PR DESCRIPTION
**Pull request by Geweldig**
- C prompt by default
- F prompt if the previous command had an exit code other than 0
- G prompt when in a git repository, followed by the branch name (in yellow) and the status (dirty in red, clean in green)

image_2017-09-06_23-59-34

### CODE REVIEW

**Comment by Geweldig** [comment]
A bug occurred with line wrapping which I have not encountered before, will fix this bug and then re-open the pull request.

**Comment by jacobpoo** [comment]
I am not grassmunk but I love this idea! However, I would recommend adding the following lines
`echo 'Microsoft(R) Windows 95'
echo '	(C)Copyright Microsoft Corp 1981-1996`

**Comment by Geweldig** [comment]
@jacobpoo This would echo these lines before every prompt, as this theme changes your PS1. Setting them to echo in your .zshrc would result in what you see in the screenshot.

**Comment by grassmunk** [comment]
This is awesome! Thank you!

**Comment by Geweldig** [comment]
Glad you like it!

**Pull request merged**
