### PR TITLE
Added script for recoloring Chicago95 (early)

### PR DESCRIPTION
**Pull request by Fierelier**
This is still pretty early and a bit of a messy script, but simple recoloring is possible:
Screenshot_20190822_224109

### CODE REVIEW

**Comment by Fierelier** [comment]
If there happens to be no interest in supplying functionality like this, or if the script is not up to standards, the merge can be closed.

**Comment by EMH-Mark-I** [comment]
I was looking through it. I haven't tested it yet though.

**Comment by Fierelier** [comment]
That's alright, I was just saying that it did not have to be accepted if there was no desire to, is all. Not meaning to be disruptive, sorry for being impatient.

**Comment by grassmunk** [comment]
TBH this is something I always wanted to tackle but didn't know how, i'm so glad you made this. I haven't had time to test it but thank you for contributing!

And don't worry about badgering us.

**Pull request merged**
