### PR TITLE
adjusting frame_border_top

### PR DESCRIPTION
**Pull request by Mugen-Houyou**
창 최대화 시 상단 보더가 숨겨지지 않는 문제를 해결합니다.
This solves the problem that the top window border won't disappear when maximized.

[https://imgur.com/a/4TLOWLd](https://imgur.com/a/4TLOWLd) ==> [https://imgur.com/a/l6e5bs1](https://imgur.com/a/l6e5bs1)

### CODE REVIEW

**Comment by grassmunk** [comment]
Does this change impact both the hidpi theme as well or just the normal theme?

**Comment by Mugen-Houyou** [comment]
> Does this change impact both the hidpi theme as well or just the normal theme?

Idk but I'll test it after sleep since it's 1 am here XD

**Comment by grassmunk** [comment]
No worries, just make that change in the HIDPI theme as well and I'll accept the merge.

**Comment by Mugen-Houyou** [comment]
Okay I'll cancel this and create a new PR with hidpi support.

**Pull request closed without merging**
