### PR TITLE
Merge Staging into Master

### PR DESCRIPTION
**Pull request by EMH-Mark-I**
I've been meaning to do this. Just need to look over it to make sure it doesn't revert back any recent commits / PRs made to master.

### CODE REVIEW

**Comment by EMH-Mark-I** [comment]
If I can just get the title right.. :-)

**Comment by grassmunk** [comment]
This is amazing! Great work!

**Comment by makeworld-the-better-one** [comment]
Can you explain the new changes? In general it'd be nice if this project used releases so I could know when to update my install.

**Comment by EMH-Mark-I** [comment]
- It addresses Issue #80 . LibreOffice GTK3 combobox and scrollbox buttons were missing; spibuttons were oversized. (It still doesn't look as good as the GTK2 version of LibreOffice, but it's a lot better now.)

- Themed some of the new XFCE 4.14 panel plugins.

- Made some adjustments to the new Thunar (GTK3 version). The Pathbar was lacking previously.

- Updated some of the CSS configuration formatting. I've been slowly trying to organize it as well as fix the indenting. Some areas have tabs that should be spaces, some areas have too many spaces, and some have none at all.

- Updated the install guide. I moved the gtk.css override instructions into a different part of the instructions as "optional." I would like to eventually get rid of the gtk overrides, but at the moment they have a nice purpose for making additional modifications to the theme.

- Updated the screenshots (except for the widget factory screenshots.That can be done later.)

**Comment by EMH-Mark-I** [comment]
At some point it would be nice to move to a release structure instead of making commits and merging PRs to the base branch whenever we feel like it. I'm moving towards making PRs with Staging now when making changes to the base branch instead of committing directly.

**Pull request merged**
