### PR TITLE
A bunch of color fixes

### PR DESCRIPTION
**Pull request by Fierelier**
Making the colors closer to the original and fixing smaller issues.

### CODE REVIEW

**Comment by EMH-Mark-I** [comment]
I'm going to take a look at this first..

**Comment by EMH-Mark-I** [comment]
I've looked over some of the changes. I would like to check if you are using the #c0c0c0 hex value for the base grey background colour? So far it looks like it. Just asking because I've had someone in the past ask me to change the base colour to the Windows 7 classic theme.

**Comment by Fierelier** [comment]
Yup. I've sourced the colors from my Windows 98 machine, not using the W2K color scheme.

**Comment by EMH-Mark-I** [comment]
Great and thanks!

**Pull request merged**
